### ISSUE TITLE
Typo in Finite Differences

### ISSUE THREAD

**Issue by dataopt** [fncbook/fnc#5]
There seems to be an undefined notation under finite differences https://fncbook.github.io/fnc/localapprox/finitediffs.html as the following image shows:
<img width="794" alt="Screen Shot 2021-09-30 at 3 41 52 PM" src="https://user-images.githubusercontent.com/28999218/135520051-e53440be-5fea-481f-a198-16c977060645.png">

The TeX command in the source is `\dd{\tilde{f}}{s}` so it looks like `\dd` is undefined.

**Comment by tobydriscoll** [comment]
Thank you! It's fixed in the production version, coming out soon.
